// <auto-generated />
using System;
using EF_CodeFirst.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_CodeFirst.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20220331153633_StudentTable_Second-try")]
    partial class StudentTable_Secondtry
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EF_CodeFirst.Models.Grade", b =>
                {
                    b.Property<int>("GradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeID"), 1L, 1);

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("GradeID");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeID = 1,
                            GradeName = "Excellent",
                            Section = "Biology",
                            StudentId = 1
                        },
                        new
                        {
                            GradeID = 2,
                            GradeName = "Very good",
                            Section = "Biology",
                            StudentId = 1
                        },
                        new
                        {
                            GradeID = 3,
                            GradeName = "Good",
                            Section = "Chemistry",
                            StudentId = 1
                        },
                        new
                        {
                            GradeID = 4,
                            GradeName = "Enough",
                            Section = "English",
                            StudentId = 1
                        },
                        new
                        {
                            GradeID = 5,
                            GradeName = "Excellent",
                            Section = "Geography",
                            StudentId = 2
                        },
                        new
                        {
                            GradeID = 6,
                            GradeName = "Very good",
                            Section = "Latin",
                            StudentId = 2
                        },
                        new
                        {
                            GradeID = 7,
                            GradeName = "Bad",
                            Section = "Mathematics",
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("EF_CodeFirst.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nchar(200)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            DateOfBirth = new DateTime(1998, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 187.72m,
                            StudentName = "Marko",
                            Weight = 85.720001220703125
                        },
                        new
                        {
                            StudentID = 2,
                            DateOfBirth = new DateTime(1994, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 168.7m,
                            StudentName = "Ana",
                            Weight = 57.75
                        });
                });

            modelBuilder.Entity("EF_CodeFirst.Models.Grade", b =>
                {
                    b.HasOne("EF_CodeFirst.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
